# Site settings
title: Sloppy Coding
subtitle: Investigating new technologies sloppy style.
author: sloppyness
email: santinijoseph@gmail.com # create separate email for blog
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: http://slopyjoe.github.io